name: Manual Deploy CRM2 (npm start)

on:
    workflow_dispatch: # manual trigger only

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js
              run: npm run build

            - name: Upload .next build
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ec2-13-201-83-62.ap-south-1.compute.amazonaws.com
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: ".next"
                  target: "/home/ec2-user/crm2"

            - name: Upload public folder
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ec2-13-201-83-62.ap-south-1.compute.amazonaws.com
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: "public"
                  target: "/home/ec2-user/crm2"

            - name: Upload package files
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ec2-13-201-83-62.ap-south-1.compute.amazonaws.com
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: "package.json,package-lock.json"
                  target: "/home/ec2-user/crm2"

            - name: Restart app (PM2)
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ec2-13-201-83-62.ap-south-1.compute.amazonaws.com
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ec2-user/crm2
                      npm install --force --omit=dev
                      pm2 restart crm2 || pm2 start npm --name "crm2" -- start
